language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - C_COMPILER=gcc-4.8
        - CXX_COMPILER=g++-4.8

env:
  matrix:
    - CONFIGURATION=Debug
    - CONFIGURATION=RelWithDebInfo
    - CONFIGURATION=MinSizeRel
    - CONFIGURATION=Release

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ../test
  - make
  - ./utf8_test
