language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=RelWithDebInfo
  - CONFIGURATION=MinSizeRel
  - CONFIGURATION=Release

osx_image:
  - xcode6.4
  - xcode8.3

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ../test
  - make
  - ./utf8_test
